blank_issues_enabled: false
contact_links:
  - name: 📘 Documentation
    url: https://fuels-react.com
    about: Visit the documentation.
  - name: 💡 Ideas for New Features, Improvements and RFCs
    url: https://github.com/0xYami/fuels-react/discussions
    about: Propose and discuss future improvements to fuels-react.
